### ISSUE TITLE
todo v0.3

### ISSUE THREAD

**Issue by davidgohel** [ardata-fr/mschart#60]
- [x] check column types when creating chart objects
- [x] check data combinations when not scatter - warn if not ok
- [x] add tests about areachart and the no "position" attribute
- [x] see how to add other label columns if possible
- [x] add tests about supported column types
- [x] add examples and details in officeverse
- [x] add unit tests about labels
- [x] add examples with unicode
- [x] don't rely on paste0("label-", name)
